name: minio-s3

networks:
  traefik_net:
    external: true

services:
  minio:
    image: quay.io/minio/minio:latest
    restart: always
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    networks:
      - traefik_net
    volumes:
      - ./data/data:/data
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.minio.rule=Host(`${TRAEFIK_HOST_MINIO}`)"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.routers.minio.tls=true"
      - "traefik.http.routers.minio.tls.certresolver=letsencrypt"
      - "traefik.http.routers.minio.tls.domains[0].main=${TRAEFIK_HOST_MINIO_MAIN}"
      - "traefik.http.services.minio_service.loadbalancer.server.port=9000"
      - "traefik.http.routers.minio.service=minio_service"

      - "traefik.http.routers.minio_console.rule=Host(`${TRAEFIK_HOST_CONSOLE}`)"
      - "traefik.http.routers.minio_console.entrypoints=websecure"
      - "traefik.http.routers.minio_console.tls=true"
      - "traefik.http.routers.minio_console.tls.certresolver=letsencrypt"
      - "traefik.http.routers.minio_console.tls.domains[0].main=${TRAEFIK_HOST_CONSOLE_MAIN}"
      - "traefik.http.services.minio_console_service.loadbalancer.server.port=9001"
      - "traefik.http.routers.minio_console.service=minio_console_service"
