name: evolution_api

services:
  evolution_api:
    image: atendai/evolution-api:v2.2.3
    restart: always
    environment:
      - SERVICE_FQDN_EVOLUTION_API_8080
      - SERVER_URL=$SERVICE_FQDN_EVOLUTION_API
      - AUTHENTICATION_API_KEY=${AUTHENTICATION_API_KEY}
      - DEL_INSTANCE=${DEL_INSTANCE:-false}
      - DATABASE_ENABLED=${DATABASE_ENABLED:-true}
      - DATABASE_PROVIDER=${DATABASE_PROVIDER:-postgresql}
      - DATABASE_CONNECTION_URI=${DATABASE_CONNECTION_URI}
      - DATABASE_CONNECTION_CLIENT_NAME=${DATABASE_CONNECTION_CLIENT_NAME:-evolution_exchange}
      - DATABASE_SAVE_DATA_INSTANCE=${DATABASE_SAVE_DATA_INSTANCE:-true}
      - DATABASE_SAVE_DATA_NEW_MESSAGE=${DATABASE_SAVE_DATA_NEW_MESSAGE:-true}
      - DATABASE_SAVE_MESSAGE_UPDATE=${DATABASE_SAVE_MESSAGE_UPDATE:-true}
      - DATABASE_SAVE_DATA_CONTACTS=${DATABASE_SAVE_DATA_CONTACTS:-true}
      - DATABASE_SAVE_DATA_CHATS=${DATABASE_SAVE_DATA_CHATS:-true}
      - DATABASE_SAVE_DATA_LABELS=${DATABASE_SAVE_DATA_LABELS:-true}
      - DATABASE_SAVE_DATA_HISTORIC=${DATABASE_SAVE_DATA_HISTORIC:-true}
      - CACHE_REDIS_ENABLED=${CACHE_REDIS_ENABLED:-true}
      - CACHE_REDIS_URI=${CACHE_REDIS_URI}
      - CACHE_REDIS_PREFIX_KEY=${CACHE_REDIS_PREFIX_KEY:-evolution}
      - CACHE_REDIS_SAVE_INSTANCES=${CACHE_REDIS_SAVE_INSTANCES:-false}
      - CACHE_LOCAL_ENABLED=${CACHE_LOCAL_ENABLED:-false}
      - S3_ENABLED=${S3_ENABLED:-false}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_PORT=${S3_PORT}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_USE_SSL=${S3_USE_SSL:-true}
      - CHATWOOT_ENABLED=${CHATWOOT_ENABLED:-false}
      - CHATWOOT_IMPORT_DATABASE_CONNECTION_URI=${CHATWOOT_IMPORT_DATABASE_CONNECTION_URI}
      - CONFIG_SESSION_PHONE_CLIENT=${CONFIG_SESSION_PHONE_CLIENT}
      - CONFIG_SESSION_PHONE_NAME=${CONFIG_SESSION_PHONE_NAME}
      - CONFIG_SESSION_PHONE_VERSION=${CONFIG_SESSION_PHONE_VERSION}
    volumes:
      - evolution_instances:/evolution/instances
