services:
  chatwoot:
    image: chatwoot/chatwoot:latest
    environment:
      - SERVICE_FQDN_CHATWOOT_3000
      - FRONTEND_URL=${SERVICE_FQDN_CHATWOOT}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DEFAULT_LOCALE=${DEFAULT_LOCALE:-pt_BR}
      - FORCE_SSL=${FORCE_SSL:-false}
      - ENABLE_ACCOUNT_SIGNUP=${ENABLE_ACCOUNT_SIGNUP:-false}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_OPENSSL_VERIFY_MODE=${REDIS_OPENSSL_VERIFY_MODE:-none}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE:-chatwoot}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MAX_THREADS=${RAILS_MAX_THREADS:-5}
      - NODE_ENV=${NODE_ENV:-production}
      - RAILS_ENV=${RAILS_ENV:-production}
      - INSTALLATION_ENV=${INSTALLATION_ENV:-docker}
      - MAILER_SENDER_EMAIL=${MAILER_SENDER_EMAIL}
      - SMTP_ADDRESS=${SMTP_ADDRESS}
      - SMTP_AUTHENTICATION=${SMTP_AUTHENTICATION}
      - SMTP_DOMAIN=${SMTP_DOMAIN}
      - SMTP_ENABLE_STARTTLS_AUTO=${SMTP_ENABLE_STARTTLS_AUTO}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_OPENSSL_VERIFY_MODE=${SMTP_OPENSSL_VERIFY_MODE:-peer}
      - ACTIVE_STORAGE_SERVICE=${ACTIVE_STORAGE_SERVICE:-local}
      - STORAGE_BUCKET_NAME=${STORAGE_BUCKET_NAME}
      - STORAGE_ACCESS_KEY_ID=${STORAGE_ACCESS_KEY_ID}
      - STORAGE_SECRET_ACCESS_KEY=${STORAGE_SECRET_ACCESS_KEY}
      - STORAGE_REGION=${STORAGE_REGION:-auto}
      - STORAGE_ENDPOINT=${STORAGE_ENDPOINT}
      - STORAGE_FORCE_PATH_STYLE=${STORAGE_FORCE_PATH_STYLE:-false}
      - DIRECT_UPLOADS_ENABLED=${DIRECT_UPLOADS_ENABLED:-false}
    entrypoint: docker/entrypoints/rails.sh
    command: 'sh -c "bundle exec rails db:chatwoot_prepare && bundle exec rails s -p 3000 -b 0.0.0.0"'
    volumes:
      - "rails-data:/app/storage"
    healthcheck:
      test:
        - CMD
        - wget
        - "--spider"
        - "-q"
        - "http://127.0.0.1:3000"
      interval: 5s
      timeout: 20s
      retries: 10

  sidekiq:
    image: chatwoot/chatwoot:latest
    environment:
      - FRONTEND_URL=${SERVICE_FQDN_CHATWOOT}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DEFAULT_LOCALE=${DEFAULT_LOCALE:-pt_BR}
      - FORCE_SSL=${FORCE_SSL:-false}
      - ENABLE_ACCOUNT_SIGNUP=${ENABLE_ACCOUNT_SIGNUP:-false}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_OPENSSL_VERIFY_MODE=${REDIS_OPENSSL_VERIFY_MODE:-none}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE:-chatwoot}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MAX_THREADS=${RAILS_MAX_THREADS:-5}
      - NODE_ENV=${NODE_ENV:-production}
      - RAILS_ENV=${RAILS_ENV:-production}
      - INSTALLATION_ENV=${INSTALLATION_ENV:-docker}
      - MAILER_SENDER_EMAIL=${MAILER_SENDER_EMAIL}
      - SMTP_ADDRESS=${SMTP_ADDRESS}
      - SMTP_AUTHENTICATION=${SMTP_AUTHENTICATION}
      - SMTP_DOMAIN=${SMTP_DOMAIN}
      - SMTP_ENABLE_STARTTLS_AUTO=${SMTP_ENABLE_STARTTLS_AUTO}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_OPENSSL_VERIFY_MODE=${SMTP_OPENSSL_VERIFY_MODE:-peer}
      - ACTIVE_STORAGE_SERVICE=${ACTIVE_STORAGE_SERVICE:-local}
      - STORAGE_BUCKET_NAME=${STORAGE_BUCKET_NAME}
      - STORAGE_ACCESS_KEY_ID=${STORAGE_ACCESS_KEY_ID}
      - STORAGE_SECRET_ACCESS_KEY=${STORAGE_SECRET_ACCESS_KEY}
      - STORAGE_REGION=${STORAGE_REGION:-auto}
      - STORAGE_ENDPOINT=${STORAGE_ENDPOINT}
      - STORAGE_FORCE_PATH_STYLE=${STORAGE_FORCE_PATH_STYLE:-false}
      - DIRECT_UPLOADS_ENABLED=${DIRECT_UPLOADS_ENABLED:-false}
    command:
      - bundle
      - exec
      - sidekiq
      - "-C"
      - config/sidekiq.yml
    volumes:
      - "sidekiq-data:/app/storage"
    healthcheck:
      test:
        - CMD-SHELL
        - "bundle exec rails runner 'puts Sidekiq.redis(&:info)' > /dev/null 2>&1"
      interval: 30s
      timeout: 10s
      retries: 3
