name: evolution_api

services:
  evolution_api:
    image: evoapicloud/evolution-api:v2.3.0
    restart: always
    environment:
      - SERVICE_FQDN_EVOLUTION_API_8080
      - SERVER_URL=$SERVICE_FQDN_EVOLUTION_API
      - AUTHENTICATION_API_KEY=${AUTHENTICATION_API_KEY}
      - DEL_INSTANCE=${DEL_INSTANCE:-false}
      - DATABASE_PROVIDER=${DATABASE_PROVIDER:-postgresql}
      - DATABASE_CONNECTION_URI=${DATABASE_CONNECTION_URI}
      - DATABASE_CONNECTION_CLIENT_NAME=${DATABASE_CONNECTION_CLIENT_NAME:-evolution_exchange}
      - CACHE_REDIS_ENABLED=${CACHE_REDIS_ENABLED:-true}
      - CACHE_REDIS_URI=${CACHE_REDIS_URI}
      - CACHE_REDIS_PREFIX_KEY=${CACHE_REDIS_PREFIX_KEY:-evolution}
      - CACHE_REDIS_TTL=${CACHE_REDIS_TTL:-604800}
      - CACHE_REDIS_SAVE_INSTANCES=${CACHE_REDIS_SAVE_INSTANCES:-false}
      - CACHE_LOCAL_ENABLED=${CACHE_LOCAL_ENABLED:-false}
      - S3_ENABLED=${S3_ENABLED:-false}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_PORT=${S3_PORT}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_USE_SSL=${S3_USE_SSL:-true}
      - S3_REGION=${S3_REGION:-auto}
      - CHATWOOT_ENABLED=${CHATWOOT_ENABLED:-false}
      - CHATWOOT_MESSAGE_READ=${CHATWOOT_MESSAGE_READ:-true}
      - CHATWOOT_MESSAGE_DELETE=${CHATWOOT_MESSAGE_DELETE:-true}
      - CHATWOOT_BOT_CONTACT=${CHATWOOT_BOT_CONTACT:-false}
      - CHATWOOT_IMPORT_DATABASE_CONNECTION_URI=${CHATWOOT_IMPORT_DATABASE_CONNECTION_URI}
      - CHATWOOT_IMPORT_PLACEHOLDER_MEDIA_MESSAGE=${CHATWOOT_IMPORT_PLACEHOLDER_MEDIA_MESSAGE:-true}
      - CONFIG_SESSION_PHONE_CLIENT=${CONFIG_SESSION_PHONE_CLIENT}
      - CONFIG_SESSION_PHONE_NAME=${CONFIG_SESSION_PHONE_NAME}
      - CONFIG_SESSION_PHONE_VERSION=${CONFIG_SESSION_PHONE_VERSION}
    volumes:
      - evolution_instances:/evolution/instances
