name: valkey

services:
  valkey:
    image: docker.io/valkey/valkey:8-alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - traefik_net
    volumes:
      - ./data/data:/data
    labels:
      - "traefik.enable=false"
